---
  kind: Service
  apiVersion: v1
  metadata:
    name: bagbeer-service
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
      service.beta.kubernetes.io/do-loadbalancer-hostname: "pk-api.lab.juiciness.io"
      service.beta.kubernetes.io/do-loadbalancer-cetificate-id: "0123d10a-c557-4ead-91d0-7d15eae83da2"
  spec:
    type: LoadBalancer
    selector:
      app: bagbeer-service
    ports:
      - name: http
        protocol: TCP
        port: 443
        targetPort: 3000
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: bagbeer-service
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: bagbeer-service
    template:
      metadata:
        labels:
          app: bagbeer-service
      spec:
        containers:
        - name: bagbeer-service
          imagePullPolicy: Always
          image: registry.digitalocean.com/merg-registry/bagbeer-service:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: PORT
              value: "3000"
            - name: POLY_ID
              valueFrom:
                secretKeyRef:
                  name: bagbeer-service-secrets
                  key: POLY_ID
            - name: AGRO_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bagbeer-service-secrets
                  key: AGRO_API_TOKEN
